NAME: "SegNet_ASPP"

SEED: 13

DATA: 
  ROOT: "../data/VOCdevkit/VOC2012"
  MODE: "train"
  PSEUDO_LABEL_FOLDER: ["Ycrf", "Yret"]
  BATCH_SIZE: 10
  CROP_SIZE: (321, 321)
  
MODEL:
  FREEZE_BN: False
  DAMP: 7. 
  LAMBDA: 0.1
  DCRF: [4, 67, 3, 3, 1] # DeepLab-V2-ASPP

SOLVER:
  LR: 2.5e-4 
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  MAX_ITER: 20000
  GAMMA: 0.9
